### ISSUE TITLE
Error when trying to install.

### ISSUE THREAD

**Issue by PorbisLorbiz** [AaronRohrbacher/klear#1]
"An Error Occurred: Cannot install 'Klear' because it points to a web page. Click [here] to finish the installation"

Whenever I hit install from the Window Manager Scripts i get this error and I am unable to download it. Can it be done manually?

**Comment by AaronRohrbacher** [comment]
Hey there, thanks for letting me know. I supplied the proper compressed package to KDE, and the issue is now resolved. 

You can use these scripts manually, yes. If you clone the repo, you can run `kpackagetool6 --type=KWin/Script -i <PATH TO THE REPO FOLDER>`
